### ISSUE TITLE
Unexpected Memory Leak

### ISSUE THREAD

**Issue by faktoral** [dliocode/SendEmail#1]
![sendmail-1](https://user-images.githubusercontent.com/1124402/183569403-ee4bdbf5-3ede-4609-99f5-aabff0f98974.jpg)

**Comment by dliocode** [comment]
Did you test with the sample?

**Comment by faktoral** [comment]
Yes, I did

**Comment by dliocode** [comment]
https://github.com/dliocode/sendemail/releases/tag/1.0.14

**Comment by faktoral** [comment]
Tested. Approved
Thanks
